services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pomodoro_user
      POSTGRES_PASSWORD: pomodoro_password
      POSTGRES_DB: pomodoro_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
